version: '3.7'
services:
  portainer:
    image: portainer/portainer-ce:2.0.1
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/portainer/data:/data'
      - '/usr/local/share/portainer:/shared'
    environment:
      - TZ=UTC
