version: '3.7'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    stdin_open: true
    tty: true
    environment:
      TZ: UTC

      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: "true"

      # Add users in the override file (not checked in)

      # set the UID for the samba share, default: ""
      USERID: "0"

      # set the GID for the samba share, default: ""
      GROUPID: "0"

      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      # SHARE: "sharename;/mnt;yes;no;no;yourname;'none';'none';'Homeserver"
      SHARE: "TimeMachine;/mnt/TimeMachine;;no;no;;none;;Time machine share on Rock Pi"
      SHARE2: "Family;/mnt/Family;;no;no;;none;;Family share on Rock Pi"
      SHARE3: "SonosMp3s;/mnt/Family/Music/mp3;;yes;;;none;;MP3s for the Sonos"

      # workgroup/domain name for share default: "MYGROUP"
      WORKGROUP: "Homeserver"

      # if set, disables recycle bin for shares
      RECYCLE: ""

      # if set, disables SMB2 minimum version
      # SMB: ""

      # For TimeMachine
      GLOBAL: "vfs objects = catia fruit streams_xattr"
      GLOBAL2: "fruit:aapl = yes"
      GLOBAL3: "fruit:time machine = yes"
      GLOBAL4: "spotlight = yes"

      # For the Sonos
      GLOBAL5: "server min protocol = NT1"
      GLOBAL6: "ntlm auth = ntlmv1-permitted"
      GLOBAL7: "map to guest = bad user"


    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /mnt/TimeMachine:/mnt/TimeMachine
      - /mnt/Family:/mnt/Family
